Repository oship-management/oship-be, pull requests merged in 2025-06, with the labels that each got.

#16 ✨ [feat] #10 결제 도메인 엔티티 추가
  src/main/java/org/example/oshipserver/domain/payment/dto/request/.gitkeep
  src/main/java/org/example/oshipserver/domain/payment/dto/request/PaymentConfirmRequestDto.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/.gitkeep
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentConfirmResponseDto.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentLookupResponseDto.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/TossPaymentConfirmResponseDto.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/TossSinglePaymentLookupResponseDto.java
  src/main/java/org/example/oshipserver/domain/payment/entity/.gitkeep
  src/main/java/org/example/oshipserver/domain/payment/entity/Payment.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentMethod.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentOrder.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentStatus.java
  src/main/java/org/example/oshipserver/domain/payment/mapper/PaymentStatusMapper.java
Labels: ✨FEAT✨

#20 ♻️ [refactor] #10 결제 도메인 피드백 반영
  src/main/java/org/example/oshipserver/domain/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentLookupResponse.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/TossPaymentConfirmResponse.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/TossSinglePaymentLookupResponse.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentOrder.java
Labels: ✨FEAT✨

#13 ✨ [feat] #11 주문 생성하기 API 구현
  src/main/java/org/example/oshipserver/domain/order/controller/.gitkeep
  src/main/java/org/example/oshipserver/domain/order/controller/OrderController.java
  src/main/java/org/example/oshipserver/domain/order/dto/OrderItemDto.java
  src/main/java/org/example/oshipserver/domain/order/dto/request/.gitkeep
  src/main/java/org/example/oshipserver/domain/order/dto/request/OrderCreateRequest.java
  src/main/java/org/example/oshipserver/domain/order/dto/response/.gitkeep
  src/main/java/org/example/oshipserver/domain/order/dto/response/OrderCreateResponse.java
  src/main/java/org/example/oshipserver/domain/order/entity/Order.java
  src/main/java/org/example/oshipserver/domain/order/entity/OrderItem.java
  src/main/java/org/example/oshipserver/domain/order/entity/OrderRecipient.java
  src/main/java/org/example/oshipserver/domain/order/entity/OrderSender.java
  src/main/java/org/example/oshipserver/domain/order/entity/RecipientAddress.java
  src/main/java/org/example/oshipserver/domain/order/entity/SenderAddress.java
  src/main/java/org/example/oshipserver/domain/order/entity/enums/CountryCode.java
  src/main/java/org/example/oshipserver/domain/order/entity/enums/OrderStatus.java
  src/main/java/org/example/oshipserver/domain/order/entity/enums/StateCode.java
  src/main/java/org/example/oshipserver/domain/order/repository/.gitkeep
  src/main/java/org/example/oshipserver/domain/order/repository/OrderRepository.java
  src/main/java/org/example/oshipserver/domain/order/service/.gitkeep
  src/main/java/org/example/oshipserver/domain/order/service/OrderService.java
  src/main/java/org/example/oshipserver/global/exception/ErrorType.java
Labels: ✨FEAT✨

#29 ✨[feat] #22 배송엔티티 구현, 배송추적엔티티 구현
  src/main/java/org/example/oshipserver/domain/shipping/entity/Shipment.java
  src/main/java/org/example/oshipserver/domain/shipping/entity/TrackingEvent.java
  src/main/java/org/example/oshipserver/domain/shipping/entity/enums/TrackingEventEnum.java
Labels: ✨FEAT✨

#34 ✨ [feat] #14 단건 결제 생성 api 구현
  .gitignore
  src/main/java/org/example/oshipserver/domain/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/org/example/oshipserver/domain/payment/entity/Payment.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentMethod.java
  src/main/java/org/example/oshipserver/domain/payment/mapper/PaymentMethodMapper.java
  src/main/java/org/example/oshipserver/domain/payment/service/PaymentService.java
  src/main/java/org/example/oshipserver/global/config/SecurityConfig.java
  src/main/java/org/example/oshipserver/global/exception/ErrorType.java
  src/main/java/org/example/oshipserver/global/exception/GlobalExceptionHandler.java
  src/main/resources/application-test.yml
Labels: ✨FEAT✨

#43 ✨ [feat] #39 Barcord Scan API 구현
  src/main/java/org/example/oshipserver/domain/order/repository/OrderRepository.java
  src/main/java/org/example/oshipserver/domain/shipping/controller/BarcodeController.java
  src/main/java/org/example/oshipserver/domain/shipping/dto/response/BarcodeValidationResponse.java
  src/main/java/org/example/oshipserver/domain/shipping/repository/ShipmentRepository.java
  src/main/java/org/example/oshipserver/domain/shipping/service/BarcodeService.java
  src/main/java/org/example/oshipserver/global/exception/ErrorType.java
Labels: ✨FEAT✨

#46 ✨ [feat] #44 Shipment Partner Measure Update
  src/main/java/org/example/oshipserver/domain/shipping/controller/ShipmentController.java
  src/main/java/org/example/oshipserver/domain/shipping/dto/request/ShipmentMeasureRequest.java
  src/main/java/org/example/oshipserver/domain/shipping/dto/response/AwbResponse.java
  src/main/java/org/example/oshipserver/domain/shipping/entity/Shipment.java
  src/main/java/org/example/oshipserver/domain/shipping/service/ShipmentService.java
Labels: ✨FEAT✨

#54 ⚡️ [fix] 배송 및 바코드스캔, 스캔후 박스측정데이터 에러수정 #47, #50 , #53 이슈
  src/main/java/org/example/oshipserver/domain/shipping/controller/BarcodeController.java
  src/main/java/org/example/oshipserver/domain/shipping/controller/ShipmentController.java
  src/main/java/org/example/oshipserver/domain/shipping/dto/request/ShipmentMeasureRequest.java
  src/main/java/org/example/oshipserver/domain/shipping/dto/response/AwbResponse.java
  src/main/java/org/example/oshipserver/domain/shipping/service/BarcodeService.java
  src/main/java/org/example/oshipserver/domain/shipping/service/ShipmentService.java
Labels: ✏️FIX✏️

#60 ♻️ [refactor] #58 toss 멱등성 키 적용
  src/main/java/org/example/oshipserver/client/toss/IdempotentRestClient.java
  src/main/java/org/example/oshipserver/client/toss/TossPaymentClient.java
  src/main/java/org/example/oshipserver/domain/payment/service/PaymentService.java
  src/main/java/org/example/oshipserver/domain/payment/util/PaymentNoGenerator.java
Labels: ✨FEAT✨, ♻️REFAC♻️

#62 ✨[feat] #59 레디스 토큰 재발급
  .gitignore
  src/main/java/org/example/oshipserver/domain/auth/controller/AuthController.java
  src/main/java/org/example/oshipserver/domain/auth/repository/RefreshTokenImpl.java
  src/main/java/org/example/oshipserver/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/org/example/oshipserver/domain/auth/service/AuthService.java
  src/main/java/org/example/oshipserver/global/common/utils/JwtUtil.java
  src/main/java/org/example/oshipserver/global/config/JwtFilter.java
Labels: ✨FEAT✨

#66 ♻️[Refac] #65 인증인가 리팩토링
  src/main/java/org/example/oshipserver/domain/auth/controller/AuthController.java
  src/main/java/org/example/oshipserver/domain/auth/dto/response/TokenResponse.java
  src/main/java/org/example/oshipserver/domain/auth/repository/RefreshTokenRepositoryImpl.java
  src/main/java/org/example/oshipserver/domain/auth/service/AuthService.java
  src/main/java/org/example/oshipserver/domain/auth/vo/AccessTokenVo.java
  src/main/java/org/example/oshipserver/domain/auth/vo/TokenValueObject.java
  src/main/java/org/example/oshipserver/domain/partner/controller/PartnerController.java
  src/main/java/org/example/oshipserver/domain/partner/service/PartnerService.java
  src/main/java/org/example/oshipserver/domain/seller/controller/SellerController.java
  src/main/java/org/example/oshipserver/domain/seller/service/SellerService.java
  src/main/java/org/example/oshipserver/global/common/utils/JwtUtil.java
  src/main/java/org/example/oshipserver/global/config/JwtFilter.java
  src/main/java/org/example/oshipserver/global/exception/ErrorType.java
Labels: ♻️REFAC♻️

#82 ♻️ [refactor] 기존의 단건결제 tossOrderId와 orderId 구분
  src/main/java/org/example/oshipserver/client/toss/TossPaymentClient.java
  src/main/java/org/example/oshipserver/domain/payment/controller/PaymentController.java
  src/main/java/org/example/oshipserver/domain/payment/dto/request/MultiPaymentConfirmRequest.java
  src/main/java/org/example/oshipserver/domain/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentLookupResponse.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentOrderListResponse.java
  src/main/java/org/example/oshipserver/domain/payment/entity/Payment.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentOrder.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentOrderRepository.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentRepository.java
  src/main/java/org/example/oshipserver/domain/payment/service/PaymentService.java
Labels: ♻️REFAC♻️

#78 ✨ [feat] #77 셀러 주문 통계 대시보드 API 구현
  build.gradle
  src/main/java/org/example/oshipserver/domain/order/controller/OrderStatsController.java
  src/main/java/org/example/oshipserver/domain/order/dto/response/OrderStatsResponse.java
  src/main/java/org/example/oshipserver/domain/order/repository/OrderRepository.java
  src/main/java/org/example/oshipserver/domain/order/service/OrderStatsService.java
  src/main/java/org/example/oshipserver/global/config/CacheConfig.java
Labels: ✨FEAT✨

#83 ✨[feat] 인터셉터 로그
  .gitignore
  src/main/java/org/example/oshipserver/domain/auth/service/AuthService.java
  src/main/java/org/example/oshipserver/domain/log/service/LogService.java
  src/main/java/org/example/oshipserver/domain/log/vo/LogInfo.java
  src/main/java/org/example/oshipserver/global/common/component/LogInterceptor.java
  src/main/java/org/example/oshipserver/global/common/utils/JwtUtil.java
  src/main/java/org/example/oshipserver/global/config/JwtFilter.java
  src/main/java/org/example/oshipserver/global/config/WebConfig.java
  src/main/resources/logback-spring.xml
  src/main/resources/logback-variables.yml
Labels: ✨FEAT✨

#85 :recycle: [refactor] 운송 가능한 order가 하나라도 있을 때는 예외처리에서 제외
  src/main/java/org/example/oshipserver/domain/carrier/service/CarrierService.java
Labels: ♻️REFAC♻️

#96 ✨ [feat] #89 주문 취소 이력 조회 api 구현
  src/main/java/org/example/oshipserver/domain/payment/controller/PaymentController.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentCancelHistoryResponse.java
  src/main/java/org/example/oshipserver/domain/payment/service/PaymentService.java
  src/main/java/org/example/oshipserver/global/exception/ErrorType.java
Labels: ✨FEAT✨

#106 ♻️[refactor] #104 에러처리 ,500 error 로그, 다중 아키텍처 빌드 추가
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/org/example/oshipserver/domain/auth/service/AuthService.java
  src/main/java/org/example/oshipserver/domain/partner/dto/response/PartnerInfoResponse.java
  src/main/java/org/example/oshipserver/domain/partner/repository/PartnerRepositoryImpl.java
  src/main/java/org/example/oshipserver/domain/partner/service/.gitkeep
  src/main/java/org/example/oshipserver/domain/partner/service/PartnerService.java
  src/main/java/org/example/oshipserver/domain/seller/dto/response/SellerInfoResponse.java
  src/main/java/org/example/oshipserver/domain/seller/repository/SellerRepositoryImpl.java
  src/main/java/org/example/oshipserver/domain/seller/service/SellerService.java
  src/main/java/org/example/oshipserver/global/common/utils/JwtUtil.java
  src/main/java/org/example/oshipserver/global/config/JwtFilter.java
  src/main/java/org/example/oshipserver/global/exception/ErrorType.java
  src/main/java/org/example/oshipserver/global/exception/GlobalExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: ♻️REFAC♻️

#110 :sparkles: [feat] #104 지역 zone 등록 기능 추가
  src/main/java/org/example/oshipserver/domain/admin/controller/AdminController.java
  src/main/java/org/example/oshipserver/domain/admin/dto/RequestZone.java
  src/main/java/org/example/oshipserver/domain/admin/service/AdminService.java
  src/main/java/org/example/oshipserver/domain/carrier/entity/CarrierCountry.java
  src/main/java/org/example/oshipserver/domain/carrier/service/AdminCarrierService.java
  src/main/java/org/example/oshipserver/global/config/SecurityConfig.java
Labels: ✨FEAT✨

#122 🚑 [hotfix] #121 Gmail 알림 발송 테스트 중단
  src/main/java/org/example/oshipserver/domain/notification/test/NotificationTest.java
Labels: 🚑HOTFIX🚑

#124 ✨ [feat] #123 사용자별로 결제 요청 내역 조회 구현 및 리팩토링
  src/main/java/org/example/oshipserver/domain/order/entity/Order.java
  src/main/java/org/example/oshipserver/domain/partner/entity/.gitkeep
  src/main/java/org/example/oshipserver/domain/payment/controller/PaymentController.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentLookupResponse.java
  src/main/java/org/example/oshipserver/domain/payment/entity/Payment.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentOrderRepository.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentRepository.java
  src/main/java/org/example/oshipserver/domain/payment/service/PaymentService.java
Labels: ✨FEAT✨, ♻️REFACTOR♻️

#131 ✨ [feat] #111 무게 별 요율 등록(엑셀)
  src/main/java/org/example/oshipserver/domain/admin/controller/AdminController.java
  src/main/java/org/example/oshipserver/domain/admin/dto/request/RateCreateRequest.java
  src/main/java/org/example/oshipserver/domain/admin/dto/request/RateExcelRequest.java
  src/main/java/org/example/oshipserver/domain/admin/dto/request/RequestZone.java
  src/main/java/org/example/oshipserver/domain/admin/dto/response/ResponseRateDto.java
  src/main/java/org/example/oshipserver/domain/admin/service/AdminService.java
  src/main/java/org/example/oshipserver/domain/carrier/entity/CarrierRateCharge.java
  src/main/java/org/example/oshipserver/domain/carrier/service/AdminCarrierService.java
  src/main/java/org/example/oshipserver/global/common/excel/AbstractExcelUploadProcessor.java
  src/main/java/org/example/oshipserver/global/common/excel/ExcelParser.java
  src/main/java/org/example/oshipserver/global/common/excel/RateExcelProcessor.java
  src/main/java/org/example/oshipserver/global/common/excel/record/ExcelParseResult.java
  src/main/resources/logback-color.xml
Labels: ✨FEAT✨

#134 :pencil2: [fix] CarrierCountry countryCode Enum 타입으로 수정
  src/main/java/org/example/oshipserver/domain/carrier/entity/CarrierCountry.java
Labels: ✏️FIX✏️

#140 ✨[feat] retry-recover 로직 구현 및 테스트 추가
  build.gradle
  src/main/java/org/example/oshipserver/client/toss/IdempotentRestClient.java
  src/main/java/org/example/oshipserver/client/toss/TossPaymentClient.java
  src/main/java/org/example/oshipserver/client/toss/TossRestTemplateConfig.java
  src/main/java/org/example/oshipserver/domain/order/entity/Order.java
  src/main/java/org/example/oshipserver/domain/order/entity/enums/OrderStatus.java
  src/main/java/org/example/oshipserver/domain/payment/dto/request/FailedTossRequestDto.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/MultiPaymentConfirmResponse.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/org/example/oshipserver/domain/payment/dto/response/TossPaymentConfirmResponse.java
  src/main/java/org/example/oshipserver/domain/payment/entity/Payment.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentFailLog.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentStatus.java
  src/main/java/org/example/oshipserver/domain/payment/mapper/PaymentMethodMapper.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentFailLogRepository.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentRepository.java
  src/main/java/org/example/oshipserver/domain/payment/service/FailedRequestRetryService.java
  src/main/java/org/example/oshipserver/domain/payment/service/PaymentFailLogService.java
  src/main/java/org/example/oshipserver/domain/payment/service/PaymentService.java
  src/main/java/org/example/oshipserver/global/common/component/RedisService.java
  src/main/java/org/example/oshipserver/global/config/RetryConfig.java
  src/main/java/org/example/oshipserver/global/exception/ApiException.java
  src/main/java/org/example/oshipserver/global/exception/ErrorType.java
  src/main/java/org/example/oshipserver/global/exception/GlobalExceptionHandler.java
  src/test/java/org/example/oshipserver/client/toss/IdempotentRestClientTest.java
  src/test/java/org/example/oshipserver/domain/order/entity/enums/OrderStatusTest.java
  src/test/java/org/example/oshipserver/domain/payment/entity/PaymentStatusTest.java
Labels: ✨FEAT✨

#159 ♻️ [refactor] 결제취소이력 테이블에서 중간 테이블(payment_orders) 참조로 구조 개선
  src/main/java/org/example/oshipserver/domain/payment/dto/response/PaymentCancelHistoryResponse.java
  src/main/java/org/example/oshipserver/domain/payment/entity/PaymentCancelHistory.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentCancelHistoryRepository.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentOrderRepository.java
  src/main/java/org/example/oshipserver/domain/payment/repository/PaymentRepository.java
  src/main/java/org/example/oshipserver/domain/payment/service/PaymentService.java
Labels: ♻️REFACTOR♻️

#160 [feat] 배송추적 스케줄러 구현
  .dockerignore
  build.gradle
  src/main/java/org/example/oshipserver/OshipServerApplication.java
  src/main/java/org/example/oshipserver/client/fedex/FedexClient.java
  src/main/java/org/example/oshipserver/client/fedex/FedexTrackingScheduler.java
  src/main/java/org/example/oshipserver/client/fedex/FedexTrackingService.java
  src/main/java/org/example/oshipserver/client/fedex/dto/FedexTrackingRequest.java
  src/main/java/org/example/oshipserver/client/fedex/dto/TrackingInfo.java
  src/main/java/org/example/oshipserver/client/fedex/dto/TrackingNumberInfo.java
  src/main/java/org/example/oshipserver/client/fedex/enums/FedexTrackingEnums.java
  src/main/java/org/example/oshipserver/domain/auth/service/AuthService.java
  src/main/java/org/example/oshipserver/domain/carrier/repository/CarrierRepository.java
  src/main/java/org/example/oshipserver/domain/log/vo/LogInfo.java
  src/main/java/org/example/oshipserver/domain/order/service/OrderService.java
  src/main/java/org/example/oshipserver/domain/partner/repository/PartnerRepository.java
  src/main/java/org/example/oshipserver/domain/seller/repository/SellerRepository.java
  src/main/java/org/example/oshipserver/domain/shipping/entity/Shipment.java
  src/main/java/org/example/oshipserver/domain/shipping/entity/TrackingEvent.java
  src/main/java/org/example/oshipserver/domain/shipping/repository/ShipmentRepository.java
  src/main/java/org/example/oshipserver/domain/shipping/repository/TrackingEventRepository.java
  src/main/java/org/example/oshipserver/global/common/component/LogInterceptor.java
  src/main/java/org/example/oshipserver/global/exception/GlobalExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: ✨FEAT✨

#166 ♻️ [refactor] # 161 Shipping API 접근 권한제한
  src/main/java/org/example/oshipserver/domain/shipping/controller/BarcodeController.java
  src/main/java/org/example/oshipserver/domain/shipping/controller/ShipmentController.java
  src/main/java/org/example/oshipserver/domain/shipping/service/BarcodeService.java
  src/main/java/org/example/oshipserver/domain/shipping/service/ShipmentService.java
  src/main/java/org/example/oshipserver/global/config/SecurityConfig.java
Labels: ♻️REFACTOR♻️

#172 ♻️ [refactor] 결제파트 외부api에러 분기처리 및 해당 테스트코드 추가
  src/main/java/org/example/oshipserver/client/toss/IdempotentRestClient.java
  src/main/java/org/example/oshipserver/client/toss/TossApiResponseErrorHandler.java
  src/main/java/org/example/oshipserver/client/toss/TossRestTemplateConfig.java
  src/main/java/org/example/oshipserver/global/config/RetryConfig.java
  src/test/java/org/example/oshipserver/client/toss/IdempotentRestClientTest.java
  src/test/java/org/example/oshipserver/client/toss/TossApiResponseErrorHandlerTest.java
Labels: ♻️REFACTOR♻️, 🧪TEST🧪
